### ISSUE TITLE
Login Page pop up

### ISSUE THREAD

**Issue by vittopan** [saundlj/AgileWebProj#20]
Hey Guys, I can't seem to figure out why the blue pop up for 'create job post' is in the header container, plus the 'you have successfully logged in' pop up. Can you guys give it a squizz. Cheers.

**Comment by saundlj** [comment]
yep thats something I included... its based in the template page. I think its a handy feature to have so the user knows they have created account (seems redundant i know but we don't do email validation or anything!) Do you want to change the style of it?
