### ISSUE TITLE
Bootstrap formatting error

### ISSUE THREAD

**Issue by tomve1tch** [saundlj/AgileWebProj#30]
There is currently a major formatting issue with bootstrap. I believe this issue is primarily on wide screens or very long screens. Needs to be resolved as is a big front end criteria.
![Screenshot 2024-05-15 182224](https://github.com/saundlj/AgileWebProj/assets/167395081/7044676d-3e6a-4930-81e0-4c96eedf2fe0)
![Screenshot 2024-05-15 182214](https://github.com/saundlj/AgileWebProj/assets/167395081/f3f83bf7-f3a1-49c7-b00e-85d272f6450a)

**Comment by tomve1tch** [comment]
@vittopan @mjb44552

**Comment by vittopan** [comment]
I tried stuffing around with it, on all different screen sizes and it still seems to work. Is anyone else having the same problem as Tom?

**Comment by vittopan** [comment]
Issue resolved, it's for overflowing content, so when you shrink the screen size now, it will create a scroll bar for the content.
