### ISSUE TITLE
Consistent interaction on pages

### ISSUE THREAD

**Issue by saundlj** [saundlj/AgileWebProj#33]
Nice interactions with the mouse on the login page, however this doesn't seem to follow to the sign up page. @mjb44552 can you check the classes so this reactivity is consistent?

**Comment by mjb44552** [comment]
On it. Vito and I decided to apply the swell to the pink boxes if they don't take up the majority of the page. I will apply it to the create account page. 

If the rest of the team thinks its best for all boxes to have the swell feature. Next team meeting we can agree to change that and I will be able to quickly implement it.

**Comment by mjb44552** [comment]
addressed in new pull requests. feel free to review code.
