### ISSUE TITLE
Formatting issue, My Job Posts

### ISSUE THREAD

**Issue by tomve1tch** [saundlj/AgileWebProj#41]
![image](https://github.com/saundlj/AgileWebProj/assets/167395081/c80eb089-17a3-4c57-a49d-ad8e424ccdc1)

Currently of the view my jobs page, the job posts are going to the right and the header and button are floating to the left. This is clearly a glitch. More... the job posts are rendering in above the page breaks and underneath the navbar and footer as per the image. Cheers @vittopan @mjb44552

**Comment by vittopan** [comment]
Hey Tom, Took the Title and create a job post out of the container and made a seperate container above its now resolved.
